Repository dkaltsios/ElCobra, pull requests merged in 2025-06, with the labels that each got.

#55 chore: update readme file
  README.md
Labels: documentation

#61 chore: update dependabot configuration file location
  .github/dependabot.yml
  .github/workflows/dependabot.yml
  CHANGELOG.md
Labels: devops

#65 chore: release version v1.3.0 into develop
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#67 hotfix: fix railway action
  .github/workflows/deploy-to-railway.yml
  CHANGELOG.md
Labels: hotfix

#69 hotfix: fix railway action by updating railway dependency installation
  .github/workflows/deploy-to-railway.yml
  CHANGELOG.md
Labels: hotfix

#71 chore: add GitHub Actions workflow to automate changelog on tag
  .github/workflows/changelog.yml
  .versionrc.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#72 feat: add royale game mode logic
  index.js
  snake/modes/royale.js
  tests/modes/royale.test.js
Labels: enhancement
