Repository dkaltsios/ElCobra, pull requests merged in 2025-05, with the labels that each got.

#38 refactor: clean up snake movement logic
  CHANGELOG.md
  index.js
  package-lock.json
  snake/collisions/avoidCollisionWithOtherSnakes.js
  snake/collisions/avoidHeadToHead.js
  snake/collisions/avoidWalls.js
  snake/collisions/preventSelfCollision.js
  snake/movement/moveTowardsClosestFood.js
  snakeMovement.js
Labels: refactor

#39 feat: add testing with jest
  CHANGELOG.md
  babel.config.js
  eslint.config.js
  jest.config.mjs
  package-lock.json
  package.json
  tests/collisions/avoidCollisionsWithOtherSnakes.test.js
Labels: enhancement

#40 feat: add heuristic evaluation
  CHANGELOG.md
  index.js
  package-lock.json
  package.json
  snake/movement/evaluateGameState.js
Labels: enhancement

#41 feat: add automatic test coverage
  CHANGELOG.md
  package-lock.json
  package.json
  tests/collisions/avoidHeadToHead.test.js
  tests/collisions/avoidWalls.test.js
  tests/collisions/preventSelfCollision.test.js
  tests/movement/evaluateGameState.test.js
  tests/movement/moveTowardsClosestFood.test.js
Labels: testing

#42 feat: implement flood fill algorithm
  CHANGELOG.md
  index.js
  snake/movement/floodFill.js
  tests/movement/floodFill.test.js
Labels: enhancement

#43 hotfix:change snake color to purple
  index.js
Labels: hotfix

#44 hotfix: change snake color to purple
  index.js
Labels: hotfix

#45 chore: release version v1.1.0
  CHANGELOG.md
  README.md
  babel.config.js
  eslint.config.js
  index.js
  jest.config.mjs
  package-lock.json
  package.json
  snake/collisions/avoidCollisionWithOtherSnakes.js
  snake/collisions/avoidHeadToHead.js
  snake/collisions/avoidWalls.js
  snake/collisions/preventSelfCollision.js
  snake/movement/evaluateGameState.js
  snake/movement/floodFill.js
  snake/movement/moveTowardsClosestFood.js
  snakeMovement.js
  tests/collisions/avoidCollisionsWithOtherSnakes.test.js
  tests/collisions/avoidHeadToHead.test.js
  tests/collisions/avoidWalls.test.js
  tests/collisions/preventSelfCollision.test.js
  tests/movement/evaluateGameState.test.js
  tests/movement/floodFill.test.js
  tests/movement/moveTowardsClosestFood.test.js
Labels: documentation, enhancement, release

#46 chore: merge version v1.1.0 into develop
  CHANGELOG.md
  package-lock.json
  snake/movement/floodFill.js
  tests/collisions/avoidHeadToHead.test.js
  tests/collisions/avoidWalls.test.js
  tests/collisions/preventSelfCollision.test.js
  tests/movement/evaluateGameState.test.js
  tests/movement/floodFill.test.js
  tests/movement/moveTowardsClosestFood.test.js
Labels: documentation, enhancement, release

#49 feature: add one move lookahead
  CHANGELOG.md
  index.js
  snake/collisions/avoidCollisionWithOtherSnakes.js
  snake/movement/simulateMove.js
  tests/movement/floodFill.test.js
  tests/movement/simulateMove.test.js
Labels: enhancement

#50 chore: release version v1.2.0
  CHANGELOG.md
  index.js
  snake/collisions/avoidCollisionWithOtherSnakes.js
  snake/movement/simulateMove.js
  tests/movement/floodFill.test.js
  tests/movement/simulateMove.test.js
Labels: release
